# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2001-2011 John Graham-Cumming
# Copyright (C) 2026 Jan Limpens
package POPFile::MQ;

use Object::Pad;
use locale;

=head1 NAME

POPFile::MQ - POPFile message queue

=head1 DESCRIPTION

This module handles POPFile's message queue. Every POPFile::Module is
able to register with the MQ for specific message types and can also
send messages without having to know which modules need to receive
its messages.

Message delivery is asynchronous and guaranteed, as well as guaranteed
first in, first out (FIFO) per process.

=head2 Public methods

=over 4

=item register()

Register for a specific message type and pass an object reference. Will
call that object's deliver() method to deliver messages.

=item post()

Send a message of a specific type.

=back

=head2 Message types

=over 4

=item UIREG

Register a UI component; message is the component type and the element
and reference to the object registering (comes from any component).

=item TICKD

Occurs when an hour has passed since the last TICKD (generated by the
POPFile::Logger module).

=item LOGIN

Occurs when a proxy logs into a remote server; the message is the
username sent.

=item COMIT

Sent when an item is committed to the history through a call to
POPFile::History::commit_slot.

=item RELSE

Sent when a session key is being released by a client.

=back

=head1 COPYRIGHT

Copyright (c) 2001-2011 John Graham-Cumming

This file is part of POPFile.

POPFile is free software; you can redistribute it and/or modify it
under the terms of version 2 of the GNU General Public License as
published by the Free Software Foundation.

POPFile is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with POPFile; if not, write to the Free Software Foundation,
Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

=cut

class POPFile::MQ :isa(POPFile::Module);

field %queue;
field %waiters;

BUILD {
    $self->set_name('mq');
}

=head1 METHODS

=head2 service()

Called to handle pending tasks for the module. Flushes all queues and
delivers pending messages to registered waiters.

=cut

method service() {
    for my $type (keys %queue) {
        my $msgs = delete $queue{$type};
        for my $msg ($msgs->@*) {
            $_->deliver($type, $msg->@*) for $waiters{$type}->@*;
        }
    }
    return 1
}

=head2 stop()

Called when POPFile is closing down. Flushes remaining items.

=cut

method stop() {
    $self->service();
}

=head2 register($type, $callback)

Register to receive messages of C<$type>. C<$callback> must be an
object whose C<deliver()> method will be called with the type and
message parameters.

=cut

method register ($type, $callback) {
    push $waiters{$type}->@*, ($callback);
}

=head2 post($type, @message)

Post a message of C<$type> with optional C<@message> parameters.

=cut

method post ($type, @msg) {
    push $queue{$type}->@*, \@msg;
}

1;
