package POPFile::MQ;

use Object::Pad;
use locale;

use POSIX ":sys_wait_h";

=head1 NAME

POPFile::MQ - POPFile message queue

=head1 DESCRIPTION

This module handles POPFile's message queue. Every POPFile::Module is
able to register with the MQ for specific message types and can also
send messages without having to know which modules need to receive
its messages.

Message delivery is asynchronous and guaranteed, as well as guaranteed
first in, first out (FIFO) per process.

=head2 Public methods

=over 4

=item register()

Register for a specific message type and pass an object reference. Will
call that object's deliver() method to deliver messages.

=item post()

Send a message of a specific type.

=back

=head2 Message types

=over 4

=item UIREG

Register a UI component; message is the component type and the element
and reference to the object registering (comes from any component).

=item TICKD

Occurs when an hour has passed since the last TICKD (generated by the
POPFile::Logger module).

=item LOGIN

Occurs when a proxy logs into a remote server; the message is the
username sent.

=item COMIT

Sent when an item is committed to the history through a call to
POPFile::History::commit_slot.

=item RELSE

Sent when a session key is being released by a client.

=back

=head1 COPYRIGHT

Copyright (c) 2001-2011 John Graham-Cumming

This file is part of POPFile.

POPFile is free software; you can redistribute it and/or modify it
under the terms of version 2 of the GNU General Public License as
published by the Free Software Foundation.

POPFile is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with POPFile; if not, write to the Free Software Foundation,
Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

=cut

class POPFile::MQ :isa(POPFile::Module) {
    # Individual queues of messages, indexed by type, written to by post().
    field %queue;

    # Registered objects for each message type.
    field %waiters;

    # Maps the PID of each active child process to its associated pipe handle.
    field %children;

    # Parent process ID, used to detect when post() is called from a child.
    field $pid = $$;

    # Writing end of the pipe when running inside a forked child process.
    field $writer = undef;

    BUILD {
        $self->set_name('mq');
    }

=head1 METHODS

=head2 service()

Called to handle pending tasks for the module. Flushes all queues and
delivers pending messages to registered waiters.

=cut

    method service() {
        # See if any of the children have passed up messages through their
        # pipes and deal with it now

        for my $kid (keys %children) {
            $self->flush_child_data($children{$kid} );
        }

        # Iterate through all the messages in all the queues

        for my $type (sort keys %queue) {
             while ( my $ref = shift @{$queue{$type}} ) {
                 my @message = @$ref;
                 my $flat = join(':', @message);

                 $self->log_msg(2, "Message $type ($flat) ready for delivery" );

                 for my $waiter (@{$waiters{$type}}) {
                    $self->log_msg(2, "Delivering message $type ($flat) to " .
                        $waiter->name() );
                    $waiter->deliver( $type, @message );
                }
            }
        }

        return 1;
    }

=head2 stop()

Called when POPFile is closing down. Flushes remaining items and closes
all child pipe handles.

=cut

    method stop() {
        # Call service() so that any remaining items are flushed and delivered

        $self->service();

        for my $kid (keys %children) {
            close $children{$kid};
            delete $children{$kid};
        }
    }

=head2 yield( $pipe, $pid )

Called by a child process to allow the parent to do work. Only does
anything when the child was not forked (i.e. C<$pid != 0>).

=cut

    method yield ($pipe, $pid) {
        if ( $pid != 0 ) {
            $self->flush_child_data( $pipe )
        }
    }

=head2 forked( $pipe_writer )

Called when some module forks POPFile, within the context of the child
process, so that this module can close any duplicated file handles that
are not needed.

C<$pipe_writer> is the writing end of a pipe that can be used to send
messages up to the parent.

=cut

    method forked ($pipe_writer = undef) {
        $writer = $pipe_writer;

        for my $kid (keys %children) {
            close $children{$kid};
            delete $children{$kid};
        }
    }

=head2 postfork( $pid, $reader )

Called in the parent process immediately after forking. Registers the
child's pipe reader handle keyed by C<$pid>.

=cut

    method postfork ($pid = undef, $reader = undef) {
        $children{"$pid"} = $reader;
        $self->log_msg(2, "Parent: postfork() called for pid $pid, reader $reader" );
    }

=head2 reaper()

Called when a child process terminates. Checks each known child with
C<waitpid()>, flushes its pipe, and removes it from the children map.

=cut

    method reaper() {
        # Look for children that have completed and then flush the data
        # from their associated pipe and see if any of our children have
        # data ready to read from their pipes,

        my @kids = keys %children;

        if ( $#kids >= 0 ) {
            for my $kid (@kids) {
                if ( waitpid( $kid, &WNOHANG ) == $kid ) {
                    $self->flush_child_data($children{$kid} );
                    close $children{$kid};
                    delete $children{$kid};

                    $self->log_msg(0, "Done with $kid (" . scalar(keys %children) . " to go)" );
                }
            }
        }
    }

=head2 read_pipe( $handle )

Reads a single message from a pipe in a cross-platform way. Returns
C<undef> if the pipe has no message ready.

=cut

    method read_pipe ($handle) {
        if ( $self->pipeready->($handle) ) {
            return <$handle>;
        }

        return undef;
    }

=head2 flush_child_data( $handle )

Flushes all pending data from a child's pipe handle, parsing each line
as a message and re-posting it into the queue.

=cut

    method flush_child_data ($handle) {
        my $stats_changed = 0;
        my $message;

        while ( defined ( $message = $self->read_pipe($handle ) ) )
        {
            if ( $message =~ /([^:]+):([^\r\n]*)/ ) {
                my @parameters = split( ':', $2 || '' );
                $self->post( $1, @parameters );
            } else {
                $self->log_msg(2, "Recieved invalid message from child: $message" );
            }
        }
    }

=head2 register( $type, $callback )

Register to receive messages of C<$type>. C<$callback> must be an
object whose C<deliver()> method will be called with the type and
message parameters.

=cut

    method register ($type, $callback) {
        push @{$waiters{$type}}, ( $callback );
    }

=head2 post( $type, @message )

Post a message of C<$type> with optional C<@message> parameters. In
the parent process the message is queued; in a child process it is
written up the pipe to the parent.

=cut

    method post ($type, @message) {
        my $flat = join( ':', @message );
        $self->log_msg(2, "post $type ($flat)" );

        # If we are in the parent process then just stick this on the queue,
        # otherwise write it up the pipe.

        if ( $$ == $pid ) {
            if ( exists( $waiters{$type} ) ) {
                $self->log_msg(2, "queuing post $type ($flat)" );
                push @{$queue{$type}}, \@message;
                $self->log_msg(2, "$type queue length now " . $#{$queue{$type}} );
            } else {
                $self->log_msg(2, "dropping post $type ($flat)" );
            }
        } else {
            return
                unless defined $writer;
            $self->log_msg(2, "sending post $type ($flat) to parent $writer" );
            print $writer "$type:$flat\n";
        }
    }
}

1;
