# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2001-2011 John Graham-Cumming and contributors
# Copyright (C) 2026 Jan Limpens
# Override translations â inherits from en-GB
LanguageCharset ISO-8859-1
LanguageDirection ltr
Language_Name English (UK)
ManualLanguage en-GB

Corpus_Color Colour
Settings_DescArchiveMessages Save a copy of every classified message to disc.
Settings_DescLogSQLToStdout Print every SQL statement with bound values to stdout. Only active when "Log to stdout" is also enabled.
Settings_LogSQLToStdout Log SQL to stdout
Settings_SectionNNTP NNTP Proxy
Settings_SectionPOP3 POP3 Proxy
Settings_SectionSMTP SMTP Proxy
